### ISSUE TITLE
No Example

### ISSUE THREAD

**Issue by AlanFoster** [stowball/react-native-bem#1]
Hey; Just came across this repository - it would be cool to see a quick example of its usage! :+1:

**Comment by stowball** [comment]
I plan to hopefully document it in the next day or 2. Stay tuned :)

**Comment by stowball** [comment]
Fixed in https://github.com/stowball/react-native-bem/commit/a5dcb17d7d879d4a2233da9a3cc5498810830fb3

**Comment by AlanFoster** [comment]
Awesome; Thanks very much :+1:
